/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Circle: THREE.Mesh
    WindMill001: THREE.Mesh
    Fence_White013: THREE.Mesh
    Wooden_Box: THREE.Mesh
    Plane: THREE.Mesh
    Well: THREE.Mesh
    Trees: THREE.Mesh
    Barn_01: THREE.Mesh
    WindMill: THREE.Mesh
  }
  materials: {
    ['default']: THREE.MeshStandardMaterial
    Farm_Pack_001: THREE.MeshStandardMaterial
  }
}

export const Farm = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('/farm.gltf') as GLTFResult
  return (
    <RigidBody type="fixed" colliders="trimesh">
      <group
        {...props}
        dispose={null}
        scale={6}
        position={[10, 0, -7]}
        rotation={[0, Math.PI, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle.geometry}
          position={[0.472, 0, -0.607]}
          scale={3.761}
        >
          <meshStandardMaterial color="#46A758" />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WindMill001.geometry}
          material={materials.Farm_Pack_001}
          position={[1.264, 1.901, 0.171]}
          scale={0.482}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fence_White013.geometry}
          material={materials.Farm_Pack_001}
          position={[1.395, -0.006, -2.471]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.099}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wooden_Box.geometry}
          material={materials.Farm_Pack_001}
          position={[0.191, 0.051, 0.211]}
          scale={0.401}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.Farm_Pack_001}
          position={[-0.169, 1.048, 0.317]}
          scale={0.03}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Well.geometry}
          material={materials.Farm_Pack_001}
          position={[2.078, 0.228, -0.058]}
          scale={[0.142, 0.128, 0.142]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trees.geometry}
          material={materials.Farm_Pack_001}
          position={[0.372, 0.148, -1.363]}
          scale={62.95}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Barn_01.geometry}
          material={materials.Farm_Pack_001}
          position={[-0.176, 0.413, -0.179]}
          scale={1.151}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WindMill.geometry}
          material={materials.Farm_Pack_001}
          position={[1.264, 1.565, 0.078]}
          scale={0.482}
        />
      </group>
    </RigidBody>
  )
}

useGLTF.preload('/farm.gltf')
