/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: inostupid (https://sketchfab.com/inostupid)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-pikachu-build-schematic-70fa30b5fee24cb5a4fc3df070500e1e
Title: Minecraft Pikachu Build Schematic
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
  }
  materials: {
    black_concrete: THREE.MeshStandardMaterial
    black_terracotta: THREE.MeshStandardMaterial
    black_wool: THREE.MeshStandardMaterial
    brown_concrete: THREE.MeshStandardMaterial
    brown_wool: THREE.MeshStandardMaterial
    coal_block: THREE.MeshStandardMaterial
    cyan_terracotta: THREE.MeshStandardMaterial
    dark_oak_planks: THREE.MeshStandardMaterial
    diorite: THREE.MeshStandardMaterial
    light_gray_wool: THREE.MeshStandardMaterial
    orange_concrete: THREE.MeshStandardMaterial
    orange_terracotta: THREE.MeshStandardMaterial
    quartz_block_bottom: THREE.MeshStandardMaterial
    quartz_block_side: THREE.MeshStandardMaterial
    quartz_block_top: THREE.MeshStandardMaterial
    red_concrete: THREE.MeshStandardMaterial
    redstone_block: THREE.MeshStandardMaterial
    white_concrete: THREE.MeshStandardMaterial
    yellow_terracotta: THREE.MeshStandardMaterial
    yellow_wool: THREE.MeshStandardMaterial
  }
}

export const Pickachu = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF(
    '/minecraft_pikachu_build_schematic.glb',
  ) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.black_concrete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.black_terracotta}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.black_wool}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.brown_concrete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.brown_wool}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.coal_block}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.cyan_terracotta}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.dark_oak_planks}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.diorite}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.light_gray_wool}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.orange_concrete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.orange_terracotta}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.quartz_block_bottom}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials.quartz_block_side}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials.quartz_block_top}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials.red_concrete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials.redstone_block}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={materials.white_concrete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_20.geometry}
          material={materials.yellow_terracotta}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials.yellow_terracotta}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials.yellow_wool}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/minecraft_pikachu_build_schematic.glb')
