/* eslint-disable react/jsx-key */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    dolmen1001: THREE.Mesh
    dolmen1: THREE.Mesh
    dolmen1002: THREE.Mesh
    dolmen1003: THREE.Mesh
    dolmen1004: THREE.Mesh
    dolmen1005: THREE.Mesh
    dolmen1006: THREE.Mesh
    dolmen1007: THREE.Mesh
    dolmen1008: THREE.Mesh
    dolmen1009: THREE.Mesh
    dolmen1010: THREE.Mesh
    dolmen1011: THREE.Mesh
    dolmen1012: THREE.Mesh
    dolmen1013: THREE.Mesh
    dolmen1014: THREE.Mesh
    dolmen1015: THREE.Mesh
    dolmen1016: THREE.Mesh
    dolmen1017: THREE.Mesh
    dolmen1018: THREE.Mesh
    dolmen1019: THREE.Mesh
    dolmen1020: THREE.Mesh
    dolmen2: THREE.Mesh
    dolmen2001: THREE.Mesh
    dolmen2002: THREE.Mesh
    dolmen2003: THREE.Mesh
    dolmen2004: THREE.Mesh
    dolmen2005: THREE.Mesh
    dolmen3: THREE.Mesh
    dolmen3001: THREE.Mesh
    dolmen3002: THREE.Mesh
    dolmen4: THREE.Mesh
    dolmen4001: THREE.Mesh
    dolmen4002: THREE.Mesh
    dolmen4003: THREE.Mesh
    dolmen4004: THREE.Mesh
    dolmen4005: THREE.Mesh
    dolmen4006: THREE.Mesh
    dolmen4007: THREE.Mesh
    dolmen4008: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
}

export const Stones = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('/stones.gltf') as GLTFResult
  const meshes = [
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1002.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1003.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1004.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1005.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1006.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1007.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1008.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1009.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1010.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1011.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1012.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1013.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1014.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1015.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1016.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1017.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1018.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1019.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen1020.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen2.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen2001.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen2002.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen2003.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen2004.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen2005.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen3.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen3001.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen3002.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen4.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen4001.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen4002.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen4003.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen4004.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen4005.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen4006.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen4007.geometry}
      material={materials.Material}
    />,
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.dolmen4008.geometry}
      material={materials.Material}
    />,
  ]
  return (
    <group {...props} dispose={null} position={[0, 1, 0]}>
      {meshes.map((mesh, index) => (
        <RigidBody
          // eslint-disable-next-line react/no-array-index-key
          key={'stone-' + index}
          colliders="hull"
          mass={10}
          type="fixed"
        >
          {mesh}
        </RigidBody>
      ))}
    </group>
  )
}

useGLTF.preload('/stones.gltf')
